# Generated by Django 4.2 on 2025-12-03 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usersignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('fname', models.CharField(max_length=10)),
                ('lname', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.BigIntegerField(max_length=10)),
                ('password', models.CharField(max_length=6)),
                ('cpassword', models.CharField(max_length=6)),
            ],
        ),
    ]
