# Generated by Django 4.2 on 2025-12-03 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersignup',
            name='cpassword',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='usersignup',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='usersignup',
            name='password',
            field=models.CharField(max_length=20),
        ),
    ]
