# Generated by Django 4.2 on 2025-12-10 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_alter_usersignup_cpassword_alter_usersignup_mobile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notesdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=20)),
                ('file', models.FileField(upload_to='NotesData')),
                ('desc', models.TextField()),
                ('status', models.TextField(choices=[('Pending', 'Pending'), ('Approve', 'Approve'), ('Reject', 'Reject')])),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.usersignup')),
            ],
        ),
    ]
