# Generated by Django 5.2.8 on 2025-12-01 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_userregister_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregister',
            name='email',
        ),
    ]
