# Generated by Django 5.2.8 on 2025-12-01 07:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_userregister_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregister',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
    ]
