# Generated by Django 4.2 on 2025-12-26 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersignup',
            name='is_member_approved',
            field=models.BooleanField(default=False),
        ),
    ]
