# Generated by Django 5.2.8 on 2025-11-21 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phnno', models.BigIntegerField()),
                ('city', models.CharField(max_length=500)),
                ('state', models.CharField(max_length=30)),
                ('zcode', models.BigIntegerField()),
                ('addr', models.TextField(max_length=500)),
                ('msg', models.TextField(max_length=500)),
            ],
        ),
    ]
